### Hidden Markov Model Common Definitions

# SOME BASIC DEFINITIONS
NYHA_CLASS_VEC = as.factor(c("II","III"))

## DEBUG LEVELS
DEBUG_LEVEL <- 0
#DEBUGLVL.ERR <- 1
#DEBUGLVL.WARN <- 2
#DEBUGLVL.INFO <- 3
DEBUGLVL.DEBUG <- 4
DEBUGLVL.ALL <- DEBUGLVL.DEBUG + 1
